# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Open PipenGeneX src Directory
      working-directory: src/csharp
      run: |
        ls -la

    - name: Change working directory
      run: | 
        cd src/csharp
      
    - name: Restore dependencies using wildcard
      run: dotnet restore $(find . -name '*.csproj')
    - name: Build
      run: dotnet build --no-restore $(find . -name '*.csproj')
    - name: Test
      run: dotnet test --no-build --verbosity normal $(find . -name '*.csproj')
